:source-highlighter: pygments
:toc:
:sectnums:
:icons: font

== 概要

このサンプルプロジェクトでは、Camel(Fuse)のロギング機能をデモします。

- Camel Route内でログ出力
- Processor内でログ出力
- ログ出力のカスタマイズ
- マスキング付きロギング
- サンプルの実行方法

== Camel Route内でログ出力

個々のCamelルート内でlogコンポーネントを呼出します。
Logコンポーネントのオプションで明示にカスタムロガー(例: `rest-request-audit`)を指定します。

下記の `<to id="rest-request-audit" ...` の記述部を参照してください。
`src/main/resources/OSGI-INF/blueprint/blueprint.xml`
```xml
<!-- Normal Logic of CamelRoute -->
<route id="route_businesslogic" streamCache="true">
    <from .../>
    <to uri="log:rest-request-audit?multiline=true&amp;showAll=true&amp;showStreams=true&amp;skipBodyLineSeparator=false"/>
    <log logName="rest-request-audit" message="${body}"/>
    <... />
</route>
```

-- rest-request-audit:: カスタムロガー名、後述のFuseロギング設定と一致させる必要があります。
-- multiline=true:: 出力時に、メッセージ(Exchange)のHeader, properties, bodyなどはそれぞれ改行して出力します。
-- showAll=true:: メッセージ(Exchange)全体を出力します。
-- showStreams=true:: メッセージBodyがStream型の場合でも文字列として読み込んで出力します。
-- skipBodyLineSeparator=false:: メッセージBodyに含まれる改行はそのまま出力します。

[WARNING]
showStreams=trueのオプションを指定した場合、メッセージBodyのStreamが一度読み込んだ後、後続処理が再度読み込めなくなります。その為、route要素にてstreamCacheを有効化する必要があります。 +
　例: `<route id="..." streamCache="true">``

== Processor内でログ出力

LoggerFactory.getLoggerでロガーを取得して、audit_log.info()で出力します。
`src/main/java/com/sample/logging/InboundProcessor.java`
```java
public class InboundProcessor implements Processor {

	private static final Logger audit_log = LoggerFactory.getLogger("rest-request-audit");

	public void init() {
		audit_log.info(InboundProcessor.class + " is initialized.");
	}
```

== ログ出力のカスタマイズ

    設定ファイル: src/main/resources/log4j.properties

1. カスタムロガーの定義
2. ルートロガーからカスタムロガーの2重出力を除外(log4j.additivity...=false)
3. カスタムロガーのレイアウト(...layout=PatternLayout)
4. その他(出力先、ローテーションなど)

```properties
#######################################
# define rest-request-audit logger
#######################################
log4j.logger.rest-request-audit=INFO, rest-request-audit
# prevent rest-request-audit logger output to rootLogger
log4j.additivity.rest-request-audit=false

# rest-request-audit appender
log4j.appender.rest-request-audit=org.apache.log4j.RollingFileAppender
log4j.appender.rest-request-audit.layout=org.apache.log4j.PatternLayout
log4j.appender.rest-request-audit.layout.ConversionPattern=%d{ABSOLUTE} | %-5.5p | %-16.16t | %-32.32c{1} | %X{bundle.id} - %X{bundle.name} - %X{bundle.version} | %m%n
log4j.appender.rest-request-audit.file=target/rest-request-audit.log
log4j.appender.rest-request-audit.append=true
log4j.appender.rest-request-audit.maxFileSize=10MB
log4j.appender.rest-request-audit.maxBackupIndex=10
#
#######################################
```



== マスキング付きロギング

下記の例では、SanitizingPatternLayoutを使って、"yyyy-mm-dd"の日付情報を一律に `__MASKED_DATE__` へ置換するようなマスキングを設定します。

[WARNING]
SanitizingPatternLayout(下記3,4,5)はKaraf上のみ指定できます。
即ち、src/main/resources/log4j.properties にて指定できません。

Fuseのロギング設定にてStep1で指定したカスタムロガー(例: `rest-request-audit`)のカスタマイズします。
また、変更の反映するには、Fuse再起動してください。

    設定ファイル: fuse/etc/org.ops4j.pax.logging.cfg

追加内容:

1. カスタムロガーの定義
2. ルートロガーからカスタムロガーの2重出力を除外(log4j.additivity...=false)
3. カスタムロガーのレイアウト(...layout=...log4j.SanitizingPatternLayout)
4. マスキング為のマッチングパターン(...layout.replaceRegex=[0-9]{4}-[0-9]{2}-[0-9]{2})
5. マスキング後の置換文字(...layout.replacement=__MASKED_DATE__)
6. その他(出力先、ローテーションなど)


```properties
#######################################
# define rest-request-audit logger
#######################################
log4j.logger.rest-request-audit=INFO, rest-request-audit
# prevent rest-request-audit logger output to rootLogger
log4j.additivity.rest-request-audit=false

# rest-request-audit appender
log4j.appender.rest-request-audit=org.apache.log4j.RollingFileAppender
log4j.appender.rest-request-audit.layout=org.apache.log4j.SanitizingPatternLayout
log4j.appender.rest-request-audit.layout.replaceRegex=[0-9]{4}-[0-9]{2}-[0-9]{2}
log4j.appender.rest-request-audit.layout.replacement=__MASKED_DATE__
log4j.appender.rest-request-audit.layout.ConversionPattern=%d{ABSOLUTE} | %-5.5p | %-16.16t | %-32.32c{1} | %X{bundle.id} - %X{bundle.name} - %X{bundle.version} | %m%n
log4j.appender.rest-request-audit.file=${karaf.data}/log/rest-request-audit.log
log4j.appender.rest-request-audit.append=true
log4j.appender.rest-request-audit.maxFileSize=10MB
log4j.appender.rest-request-audit.maxBackupIndex=10
#
#######################################
```

サンプルリクエストを発行します。
```console
$ cd camel-logging-sample
$ curl -X GET -d @request.json -H 'Content-Type:application/json' http://localhost:9002/rest/camel-logging-sample
>>> {"code":"Accepted"}
```


マスキング後の結果は以下に示します。
`log/rest-request-audit.log` には、 +
`<incidentDate>` 要素がマスキングされていることが分かります。

```text
15:11:07,283 | INFO  | tp1330437722-200 | rest-request-audit               | 232 - org.apache.camel.camel-core - 2.17.0.redhat-630283 | Exchange[
, Id: ID-JFENG-MP-51489-1505452757438-3-4
, ExchangePattern: InOut
, Properties: {CamelCharsetName=UTF-8, CamelCreatedTimestamp=Fri Sep 15 15:11:07 JST 2017, CamelMessageHistory=[DefaultMessageHistory[routeId=route4, node=restBinding4], DefaultMessageHistory[routeId=route4, node=route4], DefaultMessageHistory[routeId=route_businesslogic, node=rest-request-audit]], CamelToEndpoint=log://rest-request-audit?multiline=true&showAll=true&showStreams=true&skipBodyLineSeparator=false}
, Headers: {Accept=*/*, breadcrumbId=ID-JFENG-MP-51489-1505452757438-3-5, CamelHttpCharacterEncoding=UTF-8, CamelHttpMethod=POST, CamelHttpPath=, CamelHttpQuery=null, CamelHttpServletRequest=Request(POST /rest/camel-logging-sample)@21891042, CamelHttpServletResponse=HTTP/1.1 200

, CamelHttpUri=/rest/camel-logging-sample, CamelHttpUrl=http://localhost:9002/rest/camel-logging-sample, CamelServletContextPath=/rest/camel-logging-sample, Content-Length=189, Content-Type=application/json, Host=localhost:9002, User-Agent=curl/7.54.0}
, BodyType: com.sample.reportincident.InputReportIncident
, Body: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:inputReportIncident xmlns:ns2="http://reportincident.example.camel.apache.org">
    <incidentId>111</incidentId>
    <incidentDate>__MASKED_DATE__</incidentDate>
    <givenName>Christian</givenName>
    <familyName>Mueller</familyName>
    <email>chris@sample.com</email>
</ns2:inputReportIncident>

, Out: null:
]
```

== サンプルの実行方法

ローカルで実行の場合、
```sh
mvn camel:run
```

Karaf上で実行する場合、
先にサンプルCamelルートのデプロイは以下のコマンドを実行してください。
```sh
features:install camel-jackson
features:install camel-jetty
osgi:install -s mvn:com.sample/camel-logging-sample/1.0.0
```

`curl` でテストします。
```sh
curl http://localhost:9002/rest/camel-logging-sample
```
